[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
ordered-float = "5.1.0"
anyhow = "1.0.100"
clap = { version = "4.5.49", features = ["derive"] }
plotters = "0.3.7"
rstar = "0.12.2"
